<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "exposition_rdg"
 *
 * Auto generated by Extension Builder 2018-06-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'exposition rdg',
    'description' => 'L\'exposition.',
    'category' => 'plugin',
    'author' => 'Erwan, Maelle, Alice, Sebastien',
    'author_email' => 'trus.contact@gmail.com, maelle.richard.tci@gmail.com, alice.depinoy@gmail.com, sebastienb.rodrigues@gmail.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
